'use strict';

/**
 * @ngdoc function
 * @name gMapApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the gMapApp
 */
angular.module('gMapApp')
  .controller('MainCtrl', function ($scope) {
   var locations  = [
                {
                    "organisationId": 128,
                    "organisationName": "SOVEREIGN SUITES",
                    "latitude": -1.17408,
                    "longitude": 36.7529,
                    "roomCategoryId": 246,
                    "roomCategoryName": "Junior Suite",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 143,
                    "mealPlanName": "Half Board: HB",
                    "mealPlanAbbreviation": "HB",
                    "ppsValue": 99,
                    "sglValue": 176,
                    "childSharingValue": null,
                    "contractId": 113,
                    "contractName": "2019  Accomodation in SOVEREING SUITES CONTRACT rates for SOVEREING SUITES issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 113,
                        "name": "2019  Accomodation in SOVEREING SUITES CONTRACT rates for SOVEREING SUITES issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2020-01-01",
                        "serviceId": 128,
                        "marketId": -1,
                        "uuid": "bb279e48-9eb5-4bef-a84f-bea9db07bf42",
                        "year": 2019,
                        "issuerId": 128,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 128,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 330,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 232,
                    "organisationName": "WINDORS GOLF HOTEL AND COUNTRY CLUB",
                    "latitude": -1.21,
                    "longitude": 36.8512,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 238,
                    "organisationName": "SAFARI PARK HOTEL AND CASINO",
                    "latitude": -1.22611,
                    "longitude": 36.883,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 265,
                    "organisationName": "EKA HOTEL",
                    "latitude": -1.32417,
                    "longitude": 36.8446,
                    "roomCategoryId": 555,
                    "roomCategoryName": "SUPERIOR ROOM",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 75,
                    "sglValue": 130,
                    "childSharingValue": 37.5,
                    "contractId": 172,
                    "contractName": "2019  Accomodation in EKA HOTEL CONTRACT rates for EKA HOTEL issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 172,
                        "name": "2019  Accomodation in EKA HOTEL CONTRACT rates for EKA HOTEL issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2020-01-01",
                        "serviceId": 248,
                        "marketId": -1,
                        "uuid": "795ab35b-409c-4a1e-bb74-3d2fb03bd50e",
                        "year": 2019,
                        "issuerId": 265,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 265,
                        "lastUpdatedBy": "datamanager@safaritek",
                        "lastUpdatedOn": "2019-01-25T11:52:02.375",
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 784,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 277,
                    "organisationName": "KIMA HOTEL NAIROBI",
                    "latitude": -1.28254,
                    "longitude": 36.8307,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 283,
                    "organisationName": "HOTEL LA MADA",
                    "latitude": -1.24506,
                    "longitude": 36.8589,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 284,
                    "organisationName": "OAKWOOD HOTEL NAIROBI",
                    "latitude": -1.28405,
                    "longitude": 36.8235,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 362,
                    "organisationName": "SENTRIM 680",
                    "latitude": -1.28534,
                    "longitude": 36.8205,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 363,
                    "organisationName": "SENTRIM BOULEVARD HOTEL",
                    "latitude": -1.27518,
                    "longitude": 36.8134,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 371,
                    "organisationName": "SIGONA GOLF SUITES",
                    "latitude": -1.2234,
                    "longitude": 36.6634,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 509,
                    "organisationName": "TRIBE HOTEL",
                    "latitude": -1.22711,
                    "longitude": 36.8059,
                    "roomCategoryId": 872,
                    "roomCategoryName": "SUPERIOR ROOMS",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 100,
                    "sglValue": 180,
                    "childSharingValue": 0,
                    "contractId": 318,
                    "contractName": "2019  Accomodation in TRIBE HOTEL CONTRACT rates for TRIBE HOTEL issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 318,
                        "name": "2019  Accomodation in TRIBE HOTEL CONTRACT rates for TRIBE HOTEL issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2018-10-01",
                        "endDate": "2019-12-31",
                        "serviceId": 464,
                        "marketId": -1,
                        "uuid": "d039b850-3993-4647-b2a0-6eb873080c35",
                        "year": 2019,
                        "issuerId": 509,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 509,
                        "lastUpdatedBy": "datamanager@safaritek",
                        "lastUpdatedOn": "2019-01-25T10:53:21.444",
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 1235,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 510,
                    "organisationName": "TRADEMARK HOTEL",
                    "latitude": -1.23027,
                    "longitude": 36.8041,
                    "roomCategoryId": 880,
                    "roomCategoryName": "TRADEMARK KING/TWIN",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 70,
                    "sglValue": 120,
                    "childSharingValue": 0,
                    "contractId": 319,
                    "contractName": "2019  Accomodation in TRADEMARK HOTEL CONTRACT rates for TRADEMARK HOTEL issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 319,
                        "name": "2019  Accomodation in TRADEMARK HOTEL CONTRACT rates for TRADEMARK HOTEL issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2018-10-01",
                        "endDate": "2019-12-31",
                        "serviceId": 465,
                        "marketId": -1,
                        "uuid": "d8b9f91d-115d-4f66-96a7-033e66a996a5",
                        "year": 2019,
                        "issuerId": 510,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 510,
                        "lastUpdatedBy": "datamanager@safaritek",
                        "lastUpdatedOn": "2019-01-25T11:26:51.062",
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 1236,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 31,
                    "organisationName": "NAIROBI SERENA HOTEL",
                    "latitude": -1.287,
                    "longitude": 36.8145,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 158,
                    "organisationName": "FAIRMONT THE NORFOLK HOTEL",
                    "latitude": -1.27806,
                    "longitude": 36.8165,
                    "roomCategoryId": 330,
                    "roomCategoryName": "QECZ-Fairmont Queen NS",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 171,
                    "mealPlanName": "Bed and Breakfast: BB",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 142,
                    "sglValue": 111,
                    "childSharingValue": null,
                    "contractId": 148,
                    "contractName": "2019  Accomodation in FAIRMONT THE NORFOLK HOTEL CONTRACT rates for FAIRMONT THE NORFOLK HOTEL issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 148,
                        "name": "2019  Accomodation in FAIRMONT THE NORFOLK HOTEL CONTRACT rates for FAIRMONT THE NORFOLK HOTEL issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 153,
                        "marketId": -1,
                        "uuid": "117f363b-e3e4-40ab-842a-ccff5ce18c01",
                        "year": 2019,
                        "issuerId": 158,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 158,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 429,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 255,
                    "organisationName": "NAIROBI HILTON HOTEL",
                    "latitude": -1.28822,
                    "longitude": 36.8186,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 278,
                    "organisationName": "HOTEL LA MADA",
                    "latitude": -1.24506,
                    "longitude": 36.8589,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 280,
                    "organisationName": "KAHAMA HOTEL NAIROBI",
                    "latitude": -1.27755,
                    "longitude": 36.822,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 320,
                    "organisationName": "INTERCONTINENTAL NAIROBI",
                    "latitude": -1.28835,
                    "longitude": 36.8232,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 53,
                    "organisationName": "THE RESIDENCES AT KAREN",
                    "latitude": -1.34592,
                    "longitude": 36.7152,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 100,
                    "organisationName": "Karen Blixen Camp",
                    "latitude": -1.33986,
                    "longitude": 36.7083,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 112,
                    "organisationName": "GIRAFFE MANOR",
                    "latitude": -1.37549,
                    "longitude": 36.7447,
                    "roomCategoryId": 198,
                    "roomCategoryName": "STANDARD ROOM",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 527,
                    "sglValue": 714,
                    "childSharingValue": null,
                    "contractId": 82,
                    "contractName": "2019  Accomodation in GIRAFFE MANOR CONTRACT rates for GIRAFFE MANOR issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 82,
                        "name": "2019  Accomodation in GIRAFFE MANOR CONTRACT rates for GIRAFFE MANOR issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-16",
                        "endDate": "2020-01-15",
                        "serviceId": 115,
                        "marketId": -1,
                        "uuid": "bd8e8862-a8c6-4bf4-be89-f706f01f900d",
                        "year": 2019,
                        "issuerId": 112,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 112,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 278,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 130,
                    "organisationName": "HEMINGWAYS NAIROBI",
                    "latitude": -1.34271,
                    "longitude": 36.7053,
                    "roomCategoryId": 250,
                    "roomCategoryName": "Deluxe room",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 145,
                    "mealPlanName": "Bed and Breakfast: BB",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 238,
                    "sglValue": 290,
                    "childSharingValue": null,
                    "contractId": 114,
                    "contractName": "2019  ACCOMODATION CONTRACT rates for HEMINGWAYS NAIROBI issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 114,
                        "name": "2019  ACCOMODATION CONTRACT rates for HEMINGWAYS NAIROBI issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 132,
                        "marketId": -1,
                        "uuid": "e7774c02-805b-4016-bc2f-0947637e6bcd",
                        "year": 2019,
                        "issuerId": 130,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 130,
                        "lastUpdatedBy": "datamanager@safaritek",
                        "lastUpdatedOn": "2019-02-01T15:24:59.305",
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 338,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 147,
                    "organisationName": "VILLA ROSA KEMPINSKI NAIROBI",
                    "latitude": -1.27143,
                    "longitude": 36.8089,
                    "roomCategoryId": 297,
                    "roomCategoryName": "SUPERIOR ROOMS",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 155,
                    "mealPlanName": "Bed and Breakfast: BB",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 128,
                    "sglValue": 235,
                    "childSharingValue": null,
                    "contractId": 141,
                    "contractName": "2019  Accomodation in VILLA ROSA KEMPINSKI NAIROBI CONTRACT rates for VILLA ROSA KEMPINSKI NAIROBI issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 141,
                        "name": "2019  Accomodation in VILLA ROSA KEMPINSKI NAIROBI CONTRACT rates for VILLA ROSA KEMPINSKI NAIROBI issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 145,
                        "marketId": -1,
                        "uuid": "9b740415-0c2d-4efa-998b-dcfa4e2f200f",
                        "year": 2019,
                        "issuerId": 147,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 147,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 403,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 185,
                    "organisationName": "GLORY PALACE HOTEL",
                    "latitude": -1.27191,
                    "longitude": 36.8285,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 192,
                    "organisationName": "NAIROBI TENTED CAMP",
                    "latitude": -1.36327,
                    "longitude": 36.7765,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 216,
                    "mealPlanName": "Half Board: HB",
                    "mealPlanAbbreviation": "HB",
                    "ppsValue": 9450,
                    "sglValue": 2780,
                    "childSharingValue": null,
                    "contractId": 169,
                    "contractName": "2019  Accomodation in NAIROBI TENTED CAMP CONTRACT rates for NAIROBI TENTED CAMP issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 169,
                        "name": "2019  Accomodation in NAIROBI TENTED CAMP CONTRACT rates for NAIROBI TENTED CAMP issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2020-01-01",
                        "serviceId": 182,
                        "marketId": -1,
                        "uuid": "a792bd03-7926-4091-b8e0-f4c75deabeb5",
                        "year": 2019,
                        "issuerId": 192,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 192,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 211,
                        "currencyAbbreviation": "KES",
                        "dimensionSetId": 512,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 211,
                    "currencyAbbreviation": "KES",
                    "currencySymbol": "shs"
                },
                {
                    "organisationId": 235,
                    "organisationName": "THE PANARI RESIDENCE",
                    "latitude": -1.26198,
                    "longitude": 36.7926,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 239,
                    "organisationName": "PALACINA THE RESIDENCE AND SUITE NAIROBI HOTEL",
                    "latitude": -1.28293,
                    "longitude": 36.792,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 242,
                    "organisationName": "JACARANDA HOTEL NAIROBI",
                    "latitude": -1.26248,
                    "longitude": 36.8016,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 268,
                    "organisationName": "HOUSE OF WAINE",
                    "latitude": -1.35634,
                    "longitude": 36.7214,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 352,
                    "mealPlanName": "Full Board: null",
                    "mealPlanAbbreviation": "FB",
                    "ppsValue": 262.5,
                    "sglValue": 360,
                    "childSharingValue": null,
                    "contractId": 289,
                    "contractName": "2019  Accomodation in HOUSE OF WAINE CONTRACT rates for HOUSE OF WAINE issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 289,
                        "name": "2019  Accomodation in HOUSE OF WAINE CONTRACT rates for HOUSE OF WAINE issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 251,
                        "marketId": -1,
                        "uuid": "cc36d6ba-3e44-4f1c-922d-d35f91d5dbbd",
                        "year": 2019,
                        "issuerId": 268,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 268,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 1128,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 290,
                    "organisationName": "SANKARA HOTEL NAIROBI",
                    "latitude": -1.26271,
                    "longitude": 36.8023,
                    "roomCategoryId": 594,
                    "roomCategoryName": "SUPERIOR ROOM",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 110,
                    "sglValue": 190,
                    "childSharingValue": null,
                    "contractId": 173,
                    "contractName": "2019  Accomodation in SANKARA HOTEL NAIROBI CONTRACT rates for SANKARA HOTEL NAIROBI issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 173,
                        "name": "2019  Accomodation in SANKARA HOTEL NAIROBI CONTRACT rates for SANKARA HOTEL NAIROBI issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 270,
                        "marketId": -1,
                        "uuid": "ce3fd3fe-0ded-4d02-bb96-d3648da0fcec",
                        "year": 2019,
                        "issuerId": 290,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 290,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 785,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 293,
                    "organisationName": "FOUR POINTS BY SHERATON  HURLINGHAM",
                    "latitude": -1.2938,
                    "longitude": 36.7952,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 326,
                    "organisationName": "THE EMORY HOTEL",
                    "latitude": -1.27606,
                    "longitude": 36.7924,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 327,
                    "organisationName": "NGONG HILL HOTEL",
                    "latitude": -1.29185,
                    "longitude": 36.8104,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 328,
                    "organisationName": "WESTEND HOTEL",
                    "latitude": -1.25756,
                    "longitude": 36.7991,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 329,
                    "organisationName": "SWIS LENANA MOUNT HOTEL",
                    "latitude": -1.28994,
                    "longitude": 36.8046,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 333,
                    "organisationName": "PRIDE INN WESTLANDS",
                    "latitude": -1.26661,
                    "longitude": 36.8059,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 334,
                    "organisationName": "PRIDEINN RAPHTA",
                    "latitude": -1.26404,
                    "longitude": 36.7847,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 338,
                    "organisationName": "UTALI HOTEL",
                    "latitude": -1.26658,
                    "longitude": 36.7929,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 339,
                    "organisationName": "PRIDE INN SUITE LANTANA",
                    "latitude": -1.26658,
                    "longitude": 36.7929,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 342,
                    "organisationName": "THE CONCORD HOTEL&SUITES",
                    "latitude": -1.25456,
                    "longitude": 36.8155,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 344,
                    "organisationName": "WEST WOOD HOTEL",
                    "latitude": -1.25348,
                    "longitude": 36.8054,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 345,
                    "organisationName": "AZURE HOTEL NAIROBI",
                    "latitude": -1.26688,
                    "longitude": 36.7987,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 351,
                    "organisationName": "CROWNE PLAZA NAIROBI AIRPORT",
                    "latitude": -1.30042,
                    "longitude": 36.8156,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 358,
                    "organisationName": "ROYAL TULIP",
                    "latitude": -1.29063,
                    "longitude": 36.7898,
                    "roomCategoryId": 753,
                    "roomCategoryName": "STANDARD ROOM",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": 68,
                    "sglValue": 115,
                    "childSharingValue": null,
                    "contractId": 200,
                    "contractName": "2019  Accomodation in ROYAL TULIP CONTRACT rates for ROYAL TULIP issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 200,
                        "name": "2019  Accomodation in ROYAL TULIP CONTRACT rates for ROYAL TULIP issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2020-01-01",
                        "serviceId": 330,
                        "marketId": -1,
                        "uuid": "3e0b87f6-c62c-4d57-befd-9bafc7523ab2",
                        "year": 2019,
                        "issuerId": 358,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 358,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 844,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 397,
                    "organisationName": "RADISSON BLU",
                    "latitude": -1.30228,
                    "longitude": 36.8167,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 135,
                    "organisationName": "THE BOMA NAIROBI",
                    "latitude": -1.32415,
                    "longitude": 36.8335,
                    "roomCategoryId": 264,
                    "roomCategoryName": "Superior Room",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 150,
                    "mealPlanName": "Bed and Breakfast: BB",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 80,
                    "sglValue": 140,
                    "childSharingValue": null,
                    "contractId": 120,
                    "contractName": "2019  Accomodation in THE BOMA NAIROBI CONTRACT rates for THE BOMA NAIROBI issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 120,
                        "name": "2019  Accomodation in THE BOMA NAIROBI CONTRACT rates for THE BOMA NAIROBI issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 134,
                        "marketId": -1,
                        "uuid": "2d9a81df-0f4d-402e-9dd8-a9fc5d105f81",
                        "year": 2019,
                        "issuerId": 135,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 135,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 352,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 234,
                    "organisationName": "THE PANARI HOTEL NAIROBI",
                    "latitude": -1.32885,
                    "longitude": 36.8559,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 237,
                    "organisationName": "CANIVORE RESTURANT NAIROBI",
                    "latitude": -1.32845,
                    "longitude": 36.8005,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 285,
                    "organisationName": "HUNTERS LODGE",
                    "latitude": -2.2114,
                    "longitude": 37.7146,
                    "roomCategoryId": null,
                    "roomCategoryName": null,
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": null,
                    "mealPlanName": null,
                    "mealPlanAbbreviation": null,
                    "ppsValue": null,
                    "sglValue": null,
                    "childSharingValue": null,
                    "contractId": null,
                    "contractName": null,
                    "contractDTO": null,
                    "currencyId": null,
                    "currencyAbbreviation": null,
                    "currencySymbol": null
                },
                {
                    "organisationId": 292,
                    "organisationName": "FOUR POINTS BY SHERATON NAIROBI",
                    "latitude": -1.34111,
                    "longitude": 36.9174,
                    "roomCategoryId": 598,
                    "roomCategoryName": "TRADITIONAL KING",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 349,
                    "mealPlanName": "Bed and Breakfast: null",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 65,
                    "sglValue": 110,
                    "childSharingValue": null,
                    "contractId": 288,
                    "contractName": "2019  Accomodation in FOUR POINTS BY SHERATON NAIROBI CONTRACT rates for FOUR POINTS BY SHERATON NAIROBI issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 288,
                        "name": "2019  Accomodation in FOUR POINTS BY SHERATON NAIROBI CONTRACT rates for FOUR POINTS BY SHERATON NAIROBI issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 271,
                        "marketId": -1,
                        "uuid": "20aae812-c053-473d-b3f1-1975a512e3f1",
                        "year": 2019,
                        "issuerId": 292,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 292,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 1127,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                },
                {
                    "organisationId": 467,
                    "organisationName": "HILTON GARDEN INN",
                    "latitude": -1.35414,
                    "longitude": 36.907,
                    "roomCategoryId": 846,
                    "roomCategoryName": "HILTON STANDARD ROOM",
                    "roomCategoryAbbreviation": null,
                    "mealPlanId": 353,
                    "mealPlanName": "Bed and Breakfast: null",
                    "mealPlanAbbreviation": "BB",
                    "ppsValue": 80,
                    "sglValue": 130,
                    "childSharingValue": null,
                    "contractId": 290,
                    "contractName": "2019  Accomodation in HILTON GARDEN INN CONTRACT rates for HILTON GARDEN INN issued to SawaSawa Africa",
                    "contractDTO": {
                        "id": 290,
                        "name": "2019  Accomodation in HILTON GARDEN INN CONTRACT rates for HILTON GARDEN INN issued to SawaSawa Africa",
                        "targetId": 1,
                        "type": "CONTRACT",
                        "status": "ACTIVE",
                        "contentStatus": "DRAFT",
                        "startDate": "2019-01-01",
                        "endDate": "2019-12-31",
                        "serviceId": 429,
                        "marketId": -1,
                        "uuid": "6a7e9b92-e002-4f0b-808f-c1fd766c20f6",
                        "year": 2019,
                        "issuerId": 467,
                        "issuerName": null,
                        "issuerUuid": null,
                        "seasonGroupId": null,
                        "supplierId": 467,
                        "lastUpdatedBy": null,
                        "lastUpdatedOn": null,
                        "currencyId": 204,
                        "currencyAbbreviation": "USD",
                        "dimensionSetId": 1131,
                        "dimensionSetName": "Custom Rates Structure"
                    },
                    "currencyId": 204,
                    "currencyAbbreviation": "USD",
                    "currencySymbol": "&#36;"
                }
            ];

          $scope.highlighters = [];
          $scope.gMap = null;
          $scope.selected = null;

            // select first org in the Array
           $scope.selected = locations[0];
           console.log($scope.selected);
          
          var winInfo = new google.maps.InfoWindow({
            maxWidth: 300
          });
          
          var googleMapOption = {
            zoom: 13,
            center: new google.maps.LatLng(-1.28534, 36.8205)
            // mapTypeId: google.maps.MapTypeId.TERRAIN
          };

          $scope.gMap = new google.maps.Map(document.getElementById('googleMap'), googleMapOption);


          var createHighlighter = function(org) {
  
            var orgInfo = new google.maps.Marker({
              map: $scope.gMap,
              position: new google.maps.LatLng(org.latitude, org.longitude),
              title: ''
            });
            orgInfo.content = '<div>' +org.contractName+ '</div>';

            google.maps.event.addListener(orgInfo, 'mouseover', function () {
              winInfo.setContent('<h5>' +org.organisationName+ '</h5>' +orgInfo.content);
              winInfo.open($scope.gMap, orgInfo);
            });

            google.maps.event.addListener(orgInfo, 'mouseout', function () {
              winInfo.close($scope.gMap, orgInfo);
            });

            google.maps.event.addListener(orgInfo,'click', function (marker, i) {
                $scope.selected = angular.isNumber(org) ? $scope.highlighters(org) : org;
                 $('#org-info');
                console.log($scope.selected);
                // $scope.gMap.setZoom(12);
                // $scope.gMap.setCenter(orgInfo.getPosition());
            });

            google.maps.event.addListener(winInfo, 'domready', function (){
              
            });

            // google.maps.event.addListener(orgInfo, 'center_changed', function () {
            //     window.setTimeout(function(){
            //         $scope.gMap.panTo(orgInfo.getPosition());
            //     },100);
            // });

            $scope.highlighters.push(orgInfo);
          };
        
          for (var i = 0; i < locations.length; i++) {
            createHighlighter(locations[i]);
          }


  });
